show_temp/models.py
#coding: utf-8
from __future__ import unicode_literals, absolute_import, print_function
from django.utils.encoding import python_2_unicode_compatible
from django.db import models

# Create your models here.
class Place(models.Model):
    room = models.CharField(max_length=256)

    def __unicode__(self):
        return unicode("%s" % (self.room))


class TempMeasurmentsValues(models.Model):
    room_foreign_key = models.ForeignKey(Place)
    temp_value = models.DecimalField(max_digits=5, decimal_places=2,
        verbose_name="Temperatura")
    tepm_measurment_data = models.DateField(verbose_name="Data pomiaru")
    temp_measurment_time = models.TimeField(verbose_name="Czas poiaru")

    def __unicode__(self):
        return unicode("%s: %s %s" % (self.temp_value, self.tepm_measurment_data, self.temp_measurment_time))

show_temp/views.py
from django.shortcuts import render

# Create your views here.
import os
import datetime
from .models import TempMeasurmentsValues
from django.db.models import Avg, Max, Min
from .filter import DataFilter
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger



os.system('modprobe w1-gpio')
os.system('modprobe w1-therm')
sensor_temp = '/sys/bus/w1/devices/28-0000084be100//w1_slave'


def showActualTemp(request):
    temp_read = open(sensor_temp, 'r')
    lines = temp_read.readlines()
    temp_read.close()

    temp_find = lines[1].find('t=')
    if temp_find != -1:
        temp_strip = lines[1].strip()[temp_find + 2:]
        temp_result_cel = round(float(temp_strip) / 1000, 2)

    return render(request, 'show_temp/showing_temp.html',
    {'temp_result_cel': temp_result_cel})


class Round():#add Func
    function = 'ROUND'
    template='%(function)s(%(expressions)s, 0)'


def showTodayTemp(request):
    today_temp_measur = TempMeasurmentsValues.objects.filter(
        tepm_measurment_data=datetime.date.today()).order_by(
            'temp_measurment_time')
    today_aggregation_values = today_temp_measur.aggregate(
        Avg('temp_value'), Max('temp_value'),
        Min('temp_value'))

    return render(request, 'show_temp/today_temp.html',
    {'today_temp_measur': today_temp_measur,
    'today_aggregation_values': today_aggregation_values})


def paginacja(strona, zmienna):
    paginator = Paginator(zmienna, 24)
    try:
        page_filter = paginator.page(strona)
    except PageNotAnInteger:
        page_filter = paginator.page(1)
    except EmptyPage:
        page_filter = paginator.page(paginator.num_pages)
    return page_filter


def showMeasurmentsHistory(request):
    all_temp_measur = DataFilter(request.GET,
         queryset=TempMeasurmentsValues.objects.all().exclude(
        tepm_measurment_data__gte=datetime.date.today() - datetime.timedelta()).order_by(
            'tepm_measurment_data','temp_measurment_time'))
    page = request.GET.get('page')
    page_filter = paginacja(page, all_temp_measur.qs)

    return render(request, 'show_temp/history_temp.html',
    {'all_temp_measur': all_temp_measur, 'page_filter': page_filter})

show_temp/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Temperatur Log</title>
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
    integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.11.0/themes/smoothness/jquery-ui.css">
    <style type="text/css">
        table td {
            text-align:center !important;
            vertical-align:middle !important;
        }
        table th {
            text-align:center !important;
            vertical-align:middle !important;
        }
    </style>
  </head>
  <body>
    <div class="container-fluid"">
        <div class="row">
            <div class="col-md-4"></div>
            <div class="col-md-4">
                {% block content %}
                {% endblock %}
            </div>
            <div class="col-md-4"></div>
        </div>
    </div>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
    integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script src="http://code.jquery.com/jquery-1.10.2.js"></script>
    <script src="http://code.jquery.com/ui/1.11.0/jquery-ui.js"></script>
    <script>
      $( function() {
        $( "#id_tepm_measurment_data" ).datepicker({
          dateFormat: "yy-mm-dd"});
      } );
  </script>
  </body>
</html>

show_temp/templates/show_temp/history_temp.html
{% extends "base.html" %}
            {% block content %}
                <form action="" method="get">
                    {{ all_temp_measur.form.as_p }}
                    <button type="submit" class="btn btn-warning btn-xs">Filtruj</button>
                </form>

                <table class="table table-bordered table-striped">
                    <tr>
                        <th>Data</th>
                        <th>Godzina</th>
                        <th>Temperatura</th>
                    </tr>
                    {% for measurments in page_filter %}
                    <tr>
                        <td>{{measurments.tepm_measurment_data}}</td>
                        <td>{{measurments.temp_measurment_time}}</td>
                        <td>{{measurments.temp_value}}°C</td>
                    </tr>
                    {% endfor %}
                </table>
                <div class="pull-right">
                    <span class="pull-right">
                    {% if page_filter.has_previous %}
                        <a href="?page={{ page_filter.previous_page_number }}">poprzednia</a>
                    {% endif %}

                    <span class="current">
                    Strona {{ page_filter.number }} z {{ page_filter.paginator.num_pages }}
                    </span>

                    {% if page_filter.has_next %}
                    <a href="?page={{ page_filter.next_page_number }}">następna</a>
                    {% endif %}
                    </span>
                </div>

                <span class="pull-left"><a href="{% url 'main' %}"><button type="button" class="btn btn-warning">Return</button></a></span>
            {% endblock %}

show_temp/templates/show_temp/showing_temp.html
{% extends "base.html" %}
            {% block content %}
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h1>In: {{ temp_result_cel }}°C</h1>
                    </div>
                    <div class="panel-footer">
                        <span class="pull-left">{%now 'Y-m-j'%}</span>
                        <span class="pull-right">{%now 'H:i'%}</span>
                        <div class="clearfix"></div>
                    </div>
                </div>
                <span class="pull-left"><a href="{% url 'today' %}"><button type="button" class="btn btn-info">Today Measurments</button></a></span>
                <span class="pull-right"><a href="{% url 'history' %}"><button type="button" class="btn btn-info">Historical Measurments</button></a></span>
            {% endblock %}

show_temp/templates/show_temp/today_temp.html
{% extends "base.html" %}
            {% block content %}
                <table class="table table-bordered table-striped">
                    <tr>
                        <th>Max</th>
                        <th>Avg</th>
                        <th>Min</th>
                    </tr>
                    <tr>
                        <td>{{ today_aggregation_values.temp_value__max }}°C</td>
                        <td>{{ today_aggregation_values.temp_value__avg }}°C</td>
                        <td>{{ today_aggregation_values.temp_value__min }}°C</td>
                    </tr>
                </table>

                <table class="table table-bordered table-striped">
                    <tr>
                        <th>Data</th>
                        <th>Godzina</th>
                        <th>Temperatura</th>
                    </tr>
                    {% for measurments in today_temp_measur %}
                    <tr>
                        <td>{{measurments.tepm_measurment_data}}</td>
                        <td>{{measurments.temp_measurment_time}}</td>
                        <td>{{measurments.temp_value}}°C</td>
                    </tr>
                    {% endfor %}
                </table>
                <span class="pull-left"><a href="{% url 'main' %}"><button type="button" class="btn btn-warning">Return</button></a></span>
                <span class="pull-right"><a href="{% url 'history' %}"><button type="button" class="btn btn-info">Historical Measurments</button></a></span>
            {% endblock %}